# -*- coding: utf-8 -*-
"""CURRENCY CONVERTOR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13pzTTXKTlJ_t_OjK7QfMXAutVAxBHwmz
"""

import requests

userInput = input('Enter the amount and the currency.\n')

if(userInput[-4:] == ' USD'):
    response = requests.get('https://api.exchangeratesapi.io/latest?base=USD&symbols=INR').json()
    rate = response['rates']['INR']
    rate = float(rate)
    inputMoney = float(userInput[:-4])
    print(userInput, 'is equal to', inputMoney*rate, 'INR')
elif(userInput[-4:] == ' INR'):
    response = requests.get('https://api.exchangeratesapi.io/latest?base=INR&symbols=USD').json()
    rate = response['rates']['USD']
    rate = float(rate)
    inputMoney = float(userInput[:-4])
    print(userInput, 'is equal to', inputMoney*rate, 'USD')